version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Optional Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  spectredash:
    image: ghcr.io/edgar-treischl/spectredash
    container_name: spectredash
    ports:
      - "8000:8000"
    # No Traefik labels here — app reachable only on port 8000
