version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Optional dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app1:
    image: your-shiny-app1-image
    container_name: shiny_app1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=PathPrefix(`/app1`)"
      - "traefik.http.routers.app1.entrypoints=web"
      - "traefik.http.services.app1.loadbalancer.server.port=3838"
      - "traefik.http.routers.app1.middlewares=strip-app1"
      - "traefik.http.middlewares.strip-app1.stripprefix.prefixes=/app1"
