networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=edgar.treischl@isb.bayern.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_PROVIDER: "gitlab"
      OAUTH2_PROXY_CLIENT_ID: "aec7a136c8c16f73068e9f061249b35d6bc5cbc2de181630884678a6c027e9e6"
      OAUTH2_PROXY_CLIENT_SECRET: "gloas-65042a3cde7ab679c4ccaabb4046516eb5a151b77e1a1b83e53fad0889f7dc3d"
      OAUTH2_PROXY_COOKIE_SECRET: "MCPjYQXfVmPXt/69cbHONWJpOcvHdzFn"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_REDIRECT_URL: "https://auth.edgar-treischl.de/oauth2/callback"
      OAUTH2_PROXY_UPSTREAMS: "file:///dev/null"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_ISSUER_URL: "https://gitlab.lrz.de/oauth/authorize"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2.rule=Host(`auth.edgar-treischl.de`)"
      - "traefik.http.routers.oauth2.entrypoints=websecure"
      - "traefik.http.routers.oauth2.tls.certresolver=le"
      - "traefik.http.services.oauth2.loadbalancer.server.port=4180"
    networks:
      - web

  causalityapp:
    image: ghcr.io/edgar-treischl/causalityapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.causality.rule=Host(`causalityapp.edgar-treischl.de`)"
      - "traefik.http.routers.causality.entrypoints=websecure"
      - "traefik.http.routers.causality.tls.certresolver=le"
      - "traefik.http.services.causality.loadbalancer.server.port=3838"
      - "traefik.http.routers.causality.middlewares=auth"
      - "traefik.http.middlewares.auth.forwardauth.address=http://oauth2-proxy:4180/oauth2/auth"
      - "traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Auth-User"
    networks:
      - web
