version: '3.8'

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=edgar.treischl@isb.bayern.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    restart: unless-stopped
    command:
      - --provider=oidc
      - --oidc-issuer-url=https://gitlab.lrz.de
      - --client-id=aec7a136c8c16f73068e9f061249b35d6bc5cbc2de181630884678a6c027e9e6
      - --client-secret=gloas-768145695d9de273fcbffc6fc6bd166e91b0fe8c3339437c92a9fd68c363cc25
      - --cookie-secret=twoohh_xvL11L9MfKme9rjjR3kRJhwA_FzYjNpT7pfc=
      - --email-domain=*
      - --redirect-url=https://auth.edgar-treischl.de/oauth2/callback
      - --upstream=file:///dev/null
      - --http-address=0.0.0.0:4180
      - --set-xauthrequest=true
      - --scope=openid profile email
      - --cookie-secure=true
      - --log-level=debug
      - --pass-basic-auth=true
      - --set-auth-header=true
      - --skip-provider-button=true
      - --skip-auth-regex=^/favicon.ico$
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2.rule=Host(`auth.edgar-treischl.de`)"
      - "traefik.http.routers.oauth2.entrypoints=websecure"
      - "traefik.http.routers.oauth2.tls.certresolver=le"
      - "traefik.http.services.oauth2.loadbalancer.server.port=4180"
    networks:
      - web

  causalityapp:
    image: ghcr.io/edgar-treischl/causalityapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.causality.rule=Host(`causalityapp.edgar-treischl.de`)"
      - "traefik.http.routers.causality.entrypoints=websecure"
      - "traefik.http.routers.causality.tls.certresolver=le"
      - "traefik.http.services.causality.loadbalancer.server.port=3838"
      - "traefik.http.routers.causality.middlewares=auth"
      - "traefik.http.middlewares.auth.forwardauth.address=http://oauth2-proxy:4180/oauth2/auth"
      - "traefik.http.middlewares.auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-Auth-User"
    networks:
      - web
