version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  spectredash:
    image: ghcr.io/edgar-treischl/spectredash
    container_name: spectredash
    ports:
      - "8000:8000"

  causalityapp:
    image: ghcr.io/edgar-treischl/causalityapp 
    container_name: causalityapp
    ports:
      - "8001:3838"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.causality.rule=PathPrefix(`/causality`)"
      - "traefik.http.routers.causality.entrypoints=web"
      - "traefik.http.services.causality.loadbalancer.server.port=3838"
      - "traefik.http.routers.causality.middlewares=auth,strip-causality"
      - "traefik.http.middlewares.strip-causality.stripprefix.prefixes=/causality"
      - "traefik.http.middlewares.auth.basicauth.users=edgar:$apr1$/5SVg.Dy$8UV5LGWWaDU82MP468X2z/"
