version: "3.8"

services:
  spectrapp:
    image: gitlab.lrz.de:5005/edgar-treischl/sp3ctrapp
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - internal

  causality-proxy:
    image: nginx:alpine
    container_name: causality-proxy
    ports:
      - "8181:80"  # Access app at http://IP:8181
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - spectrapp
    networks:
      - internal

networks:
  internal:
    driver: bridge