version: "3.8"

networks:
  web:
    external: true

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--api.insecure=false"  # Disable insecure API access
      - "--api.dashboard=true"  # Enable dashboard
      - "--providers.docker=true"  # Enable Docker provider
      - "--providers.file.directory=/etc/traefik/dynamic"  # Dynamic config directory for file provider
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.email=edgar.treischl@isb.bayern.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./dynamic:/etc/traefik/dynamic"  # Mount dynamic config files here
    networks:
      - web
    labels:
      # Traefik dashboard on traefik.edgar-treischl.de
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.edgar-treischl.de`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.middlewares=auth-dashboard@file"   # Reference middleware from file provider

  causalityapp:
    image: ghcr.io/edgar-treischl/causalityapp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.causality.rule=Host(`causalityapp.edgar-treischl.de`)"
      - "traefik.http.routers.causality.entrypoints=websecure"
      - "traefik.http.routers.causality.tls.certresolver=le"
      - "traefik.http.routers.causality.middlewares=auth-causality@file"  # Reference middleware from file provider
      - "traefik.http.services.causality.loadbalancer.server.port=3838"
    networks:
      - web
